# docker-compose.yml
version: "3.8"

services:
  diabetes-api:
    build: .
    container_name: diabetes-api
    ports:
      - "8000:8000"
    # Dev: mount code for live reload
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
